# Generated by Django 5.2.6 on 2025-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='new_Field',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
