# Generated by Django 5.2.6 on 2025-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0002_usersignup_new_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=400)),
                ('message', models.TextField(max_length=4000)),
                ('toAddress', models.TextField()),
                ('fromAddress', models.EmailField(max_length=254)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
